on:
  push:
    branches:
      - 'fake-master'
jobs:
  blockers-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script
        run: ./.github/workflows/blocker-tracker-script.sh
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          SLACK_WEB_HOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }}
