name: On Push

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Ant All
        run: ant all

      - name: Run Format Source Script
        run: ./test.sh